apiVersion: v2
appVersion: 1.16.0
dependencies:
- alias: tradeHistoryDB
  name: mongodb
  repository: https://charts.bitnami.com/bitnami/
  version: 7.4.2
- alias: tradeTransactionalDB
  name: mariadb
  repository: https://charts.bitnami.com/bitnami/
  version: 7.4.2
description: Traderlite App
name: traderlite
type: application
version: "1.4"
