apiVersion: v2
dependencies:
- alias: tradeTransactionalDB
  name: mariadb
  repository: https://charts.bitnami.com/bitnami/
  version: 7.4.2
- alias: tradeHistoryDB
  name: mongodb
  repository: https://charts.bitnami.com/bitnami/
  version: 7.4.2
- alias: localMQ
  condition: kafkaIntegration.enabled
  name: ibm-mqadvanced-server-dev
  repository: https://raw.githubusercontent.com/IBM/charts/master/repo/stable/
  version: 6.0.0
- condition: kafkaIntegration.enabled
  name: kafkaConnect
  repository: file://kafkaConnect
  version: 1.0.0
description: A Helm chart for Kubernetes
name: traderlite
type: application
version: 1.0.1
