apiVersion: apps/v1
kind: Deployment
metadata:
  name: traderlite-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: traderlite-operator
  template:
    metadata:
      labels:
        name: traderlite-operator
    spec:
      serviceAccountName: traderlite-operator
      containers:
        - name: traderlite-operator
          # Replace this with the built image name
          image: quay.io/clouddragons/traderlite-operator:latest
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "traderlite-operator"
