apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-credentials
stringData:
  mariadb.db.id: {{ .Values.mariadb.db.user }}
  mariadb.db.pwd: {{ .Values.mariadb.db.password }}
  mongodb.db.id: {{ .Values.mongodb.mongodbUsername }}
  mongodb.db.pwd: {{ .Values.mongodb.mongodbPassword }}
  apic.stockQuote.clientId: {{ .Values.stockQuote.apic.clientId }}
{{- if .Values.kafkaIntegration.enabled }}
  mq.user: {{ .Values.mqaccess.user }}
  mq.password: {{ .Values.mqaccess.password }}
{{- end }}
{{- if .Values.salesforceIntegration.enabled }}
  salesforce.flow.apiKey: {{ .Values.salesforceIntegration.flow.apiKey }}
{{- end }}
