#       Copyright 2017 IBM Corp All Rights Reserved

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

#Deploy the pod
{{- if and .Values.kafkaIntegration.enabled .Values.kafkaConnectStandalone.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kafka-connect-standalone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-kafka-connect-standalone
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-kafka-connect-standalone
        solution: {{ .Release.Name }}-lite-trader
    spec:
      containers:
      - name: kafka-connect-standalone
        image: "{{ .Values.kafkaConnectStandalone.image.repository }}:{{ .Values.kafkaConnectStandalone.image.tag }}"
        volumeMounts:
        - mountPath: "/opt/kafka/mountedconfig"
          name: kckeystore
        resources:
          limits:
            cpu: 600m
            memory: 500Mi
          requests:
            cpu: 600m
            memory: 500Mi

        imagePullPolicy: Always
        imagePullPolicy: {{ .Values.kafkaConnectStandalone.image.pullPolicy }}
      {{- if .Values.kafkaConnectStandalone.image.pullSecrets }}
        imagePullSecrets:
         - name: {{ .Values.kafkaConnectStandalone.image.pullSecrets }}
      {{- end }}
        securityContext:
          capabilities: {}
          privileged: false
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      volumes:
      - name: kckeystore
        secret:
          secretName: {{ .Release.Name }}-kafka-credentials
{{- end }}
