apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
{{- if .Values.kafkaIntegration.enabled }}
  kafka.integration.state: "enabled"
  mq.qname: "{{ .Values.mqaccess.qname }}"
  mq.qmgr: "{{ .Values.mqaccess.qmgr }}"
  mq.listener: "{{ .Values.mqaccess.listener }}"
  mq.channel: "{{ .Values.mqaccess.channel }}"
  mq.user: "user"
  mq.password: "passw0rd"
{{- else }}
  kafka.integration.state: "disabled"
{{- end }}
{{- if .Values.salesforceIntegration.enabled }}
  salesforce.integration.state: "enabled"
  salesforce.flow.url: "{{ .Values.salesforceIntegration.flow.url }}"
  salesforce.flow.path: "{{ .Values.salesforceIntegration.flow.path }}"
{{- else }}
  salesforce.integration.state: "disabled"
{{- end }}
  mariadb.db.name: "{{ .Values.tradeTransactionalDB.db.name }}"
  mariadb.db.port: "{{ .Values.tradeTransactionalDB.service.port }}"
  mariadb.db.host: "{{ .Release.Name }}-mariadb"
  mongodb.db.name: "{{ .Values.tradeHistoryDB.mongodbDatabase }}"
  mongodb.db.port: "{{ .Values.tradeHistoryDB.service.port }}"
  mongodb.db.host: "{{ .Release.Name }}-mongodb"
  apic.stockQuote.url: "{{ .Values.stockQuoteMicroservice.apic.url }}"
  tradeHistory.url: "http://{{ .Release.Name }}-trade-history-service:5000"
  stockQuote.url: "http://{{ .Release.Name }}-stock-quote-service:9080"
  portfolio.url: "http://{{ .Release.Name }}-portfolio-service:8080"
