{{- if .Values.kafkaIntegration.enabled }}
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaConnect
metadata:
  name: {{ .Values.kafkaConnect.cluster }}
  annotations:
    eventstreams.ibm.com/use-connector-resources: "true"
spec:
  replicas: 1
  bootstrapServers: "{{ .Values.kafkaAccess.bootstrapHost }}"
  image: quay.io/clouddragons/traderlite-kafka-connect:latest
  template:
    pod:
      imagePullSecrets: []
      metadata:
        annotations:
          eventstreams.production.type: CloudPakForIntegrationNonProduction
          productID: 2a79e49111f44ec3acd89608e56138f5
          productName: IBM Event Streams for Non Production
#          productVersion: 11.0.4
          productVersion: 11.1.5
          productMetric: VIRTUAL_PROCESSOR_CORE
          productChargedContainers: {{ .Values.kafkaConnect.cluster }}-connect
          cloudpakId: c8b82d189e7545f0892db9ef2731b90d
          cloudpakName: IBM Cloud Pak for Integration
 #         cloudpakVersion: 2022.2.1
          productCloudpakRatio: "2:1"


  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
{{- end }}
