#       Copyright 2017 IBM Corp All Rights Reserved

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

#Deploy the pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-trade-history
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-trade-history

  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-trade-history
        solution: {{ .Release.Name }}-lite-trader
    spec:
      containers:
      - name: trade-history
{{ if .Values.tradeHistoryMicroservice }}
        image: "{{ .Values.tradeHistoryMicroservice.image.repository }}:{{ .Values.tradeHistoryMicroservice.image.tag }}"
{{ else }}
        image: "quay.io/clouddragons/trade-history-python:2.0"
{{ end }}
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: mongodb.db.host
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name:  {{ .Release.Name }}-config
                key: mongodb.db.port
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: mongodb.db.name
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-credentials
                key: mongodb.db.id
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-credentials
                key: mongodb.db.pwd

        ports:
          - containerPort: 5000
{{ if .Values.tradeHistoryMicroservice }}
        imagePullPolicy: {{ .Values.tradeHistoryMicroservice.image.pullPolicy }}
      {{- if .Values.tradeHistoryMicroservice.image.pullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.tradeHistoryMicroservice.image.pullSecrets }}
      {{- end }}
{{ else }}
        imagePullPolicy: IfNotPresent
{{ end }}
---
#Deploy the service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-trade-history-service

spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: {{ .Release.Name }}-trade-history
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-trade-history
  annotations:
    description: Route for application's http service
    haproxy.router.openshift.io/disable_cookies: 'false'
spec:
  path: '/trade-history'
  port:
    targetPort: 5000
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Release.Name }}-trade-history-service
